// <auto-generated />
namespace HonorsProject.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnsertypoFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnsertypoFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201912301145020_AnsertypoFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
